name: Release & Publish

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1